import { test, expect } from "@playwright/test";

test("real PostgreSQL: calendar persists across reload and public guest booking", async ({ page, browser }) => {
  test.setTimeout(60000);
  test.skip(!process.env.CALENDAR_E2E_PASSWORD || test.info().project.name !== "desktop", "Use only the isolated calendar test database; mobile UI is covered separately");
  await page.goto("/login");
  await page.locator('input[type="email"]').fill("calendar-e2e@example.org");
  await page.locator('input[type="password"]').fill(process.env.CALENDAR_E2E_PASSWORD!);
  await page.getByRole("button", { name: "Войти", exact: true }).click();
  await page.waitForURL(/\/dashboard/);
  const bearer = await page.evaluate(() => localStorage.getItem("access_token"));
  await page.request.put("/api/v1/recruitment/availability/rules", { headers: { Authorization: `Bearer ${bearer}` }, data: { rules: [], timezone: "Asia/Yekaterinburg", buffer_minutes: 0 } });
  await page.request.delete("/api/v1/recruitment/public-link", { headers: { Authorization: `Bearer ${bearer}` } });
  await page.goto("/dashboard/calendar");
  await page.getByRole("button", { name: "Доступность", exact: true }).click();
  await page.getByRole("switch", { name: "Доступность: Понедельник", exact: true }).click();
  await page.getByRole("button", { name: "Сохранить настройки" }).click();
  await expect(page.getByText("Изменения сохранены", { exact: true })).toBeVisible();
  await page.getByRole("tab", { name: "Публичная ссылка" }).click();
  await page.getByRole("switch", { name: "Публичная запись", exact: true }).click();
  await expect(page.locator(".share-box > div span")).toContainText("/book/");
  const link = await page.locator(".share-box > div span").innerText();
  expect(link).toContain("/book/");
  await page.getByRole("button", { name: "Закрыть", exact: true }).last().click();
  await page.reload();
  await page.getByRole("button", { name: "Доступность", exact: true }).click();
  await expect(page.getByRole("switch", { name: "Доступность: Понедельник", exact: true })).toHaveAttribute("aria-checked", "true");
  await page.getByRole("button", { name: "Закрыть", exact: true }).last().click();

  const guest = await browser.newContext({ timezoneId: "America/New_York" });
  const publicPage = await guest.newPage();
  await publicPage.goto(link);
  await expect(publicPage.getByRole("heading", { name: "Выберите удобное время" })).toBeVisible();
  await expect(publicPage.getByText(/America\/New_York/)).toBeVisible();
  await publicPage.locator(".booking-dates button").first().click();
  await publicPage.locator(".slot-groups button").first().click();
  const visitor = `Посетитель ${Date.now()}`;
  await publicPage.getByLabel("Ваше имя").fill(visitor);
  await publicPage.getByLabel("Электронная почта").fill("visitor@example.org");
  await publicPage.getByRole("button", { name: "Подтвердить запись" }).click();
  await expect(publicPage.getByText("ЗАПИСЬ ПОДТВЕРЖДЕНА")).toBeVisible();
  await page.locator('input[aria-label="Открыть день"]').fill(new Date(Date.now() + ((8 - new Date().getDay()) % 7 || 7) * 86400000).toLocaleDateString("sv-SE"));
  await expect(page.getByRole("button").filter({ hasText: visitor })).toBeVisible();
  await page.reload();
  // The selected date is UI state; meetings are loaded again for the same week.
  await page.locator('input[aria-label="Открыть день"]').fill(new Date(Date.now() + ((8 - new Date().getDay()) % 7 || 7) * 86400000).toLocaleDateString("sv-SE"));
  const meeting = page.getByRole("button").filter({ hasText: visitor });
  await meeting.click();
  await page.getByRole("button", { name: "Редактировать", exact: true }).click();
  await page.getByLabel("Название встречи").fill(`Изменено ${visitor}`);
  await page.getByRole("button", { name: "Сохранить", exact: true }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.getByRole("button").filter({ hasText: `Изменено ${visitor}` }).click();
  await page.getByRole("button", { name: "Отменить встречу" }).click();
  await page.getByRole("button", { name: "Подтвердить отмену" }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await expect(page.getByRole("button").filter({ hasText: visitor })).not.toBeVisible();
  await guest.close();
});
