import { test, expect } from "@playwright/test";

test("real PostgreSQL: department rename and optional fields persist", async ({ page }) => {
  test.skip(!process.env.PREVIEW_ADMIN_PASSWORD, "Run explicitly against the isolated preview database");
  const name = `Отдел ${test.info().project.name} ${Date.now()}`;
  await page.goto("/login");
  await page.locator('input[type="email"]').fill("hr@preview.example.org");
  await page.locator('input[type="password"]').fill(process.env.PREVIEW_ADMIN_PASSWORD!);
  await page.getByRole("button", { name: "Войти", exact: true }).click();
  await page.waitForURL(/\/dashboard/);
  if (new URL(page.url()).pathname === "/dashboard/start") await page.getByRole("button", { name: "Перейти к работе", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Рабочий стол", exact: true })).toBeVisible();
  await page.goto("/dashboard/organization");
  await page.getByRole("button", { name: "Создать отдел", exact: true }).click();
  await page.getByLabel("Название отдела *", { exact: true }).fill(name);
  await page.getByLabel("Описание", { exact: true }).fill("Описание");
  await page.getByLabel("Руководитель", { exact: true }).selectOption({ index: 1 });
  await page.getByRole("button", { name: "Создать", exact: true }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.getByRole("button", { name: `Редактировать отдел ${name}`, exact: true }).click();
  await page.getByLabel("Название отдела *", { exact: true }).fill(`${name} обновлено`);
  await page.getByLabel("Описание", { exact: true }).fill("");
  await page.getByLabel("Руководитель", { exact: true }).selectOption("");
  await page.getByRole("button", { name: "Сохранить", exact: true }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.reload();
  await page.getByRole("button", { name: `Редактировать отдел ${name} обновлено`, exact: true }).click();
  await expect(page.getByLabel("Название отдела *", { exact: true })).toHaveValue(`${name} обновлено`);
  await expect(page.getByLabel("Описание", { exact: true })).toHaveValue("");
  await expect(page.getByLabel("Руководитель", { exact: true })).toHaveValue("");
});

test("real PostgreSQL: position edit persists and clears department and description", async ({ page }) => {
  test.skip(!process.env.PREVIEW_ADMIN_PASSWORD, "Run explicitly against the isolated preview database");
  const name = `Должность ${test.info().project.name} ${Date.now()}`;
  await page.goto("/login");
  await page.locator('input[type="email"]').fill("hr@preview.example.org");
  await page.locator('input[type="password"]').fill(process.env.PREVIEW_ADMIN_PASSWORD!);
  await page.getByRole("button", { name: "Войти", exact: true }).click();
  await page.waitForURL(/\/dashboard/);
  if (new URL(page.url()).pathname === "/dashboard/start") await page.getByRole("button", { name: "Перейти к работе", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Рабочий стол", exact: true })).toBeVisible();
  await page.goto("/dashboard/positions");
  await page.getByRole("button", { name: "Создать должность", exact: true }).click();
  await page.getByLabel("Название должности *", { exact: true }).fill(name);
  await page.getByLabel("Описание", { exact: true }).fill("Описание");
  await page.getByLabel("Отдел", { exact: true }).selectOption({ index: 1 });
  await page.getByLabel("Добавить навык").fill("Excel");
  await page.getByRole("button", { name: "Создать", exact: true }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.getByRole("button", { name: `Редактировать должность ${name}`, exact: true }).click();
  await page.getByLabel("Название должности *", { exact: true }).fill(`${name} обновлено`);
  await page.getByLabel("Описание", { exact: true }).fill("");
  await page.getByLabel("Отдел", { exact: true }).selectOption("");
  await page.getByRole("button", { name: "Удалить навык Excel" }).click();
  await page.getByRole("button", { name: "Сохранить", exact: true }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.reload();
  await page.getByRole("button", { name: `Редактировать должность ${name} обновлено`, exact: true }).click();
  await expect(page.getByLabel("Описание", { exact: true })).toHaveValue("");
  await expect(page.getByLabel("Отдел", { exact: true })).toHaveValue("");
  await expect(page.getByRole("button", { name: "Удалить навык Excel" })).toHaveCount(0);
  await page.getByRole("button", { name: "Отмена", exact: true }).click();
});

test("real PostgreSQL: vacancy, candidate, interview, hire and lesson assignment", async ({ page }) => {
  test.setTimeout(45000);
  test.skip(!process.env.PREVIEW_ADMIN_PASSWORD, "Run explicitly against the isolated preview database");
  const name = `Проверка ${test.info().project.name} ${Date.now()}`;
  await page.goto("/login");
  await page.locator('input[type="email"]').fill("hr@preview.example.org");
  await page.locator('input[type="password"]').fill(process.env.PREVIEW_ADMIN_PASSWORD!);
  await page.getByRole("button", { name: "Войти", exact: true }).click();
  await page.waitForURL(/\/dashboard/);
  if (new URL(page.url()).pathname === "/dashboard/start") await page.getByRole("button", { name: "Перейти к работе", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Рабочий стол", exact: true })).toBeVisible();
  await page.goto("/dashboard/recruitment?tab=vacancies");
  await page.getByRole("button", { name: "Новая вакансия", exact: true }).click();
  await page.getByLabel("Название", { exact: true }).fill(name);
  await page.getByLabel("Должность", { exact: true }).selectOption({ label: "Бухгалтер" });
  await page.getByRole("button", { name: "Создать", exact: true }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.getByRole("button", { name: "Добавить кандидата" }).click();
  await page.getByLabel("ФИО", { exact: true }).fill(name);
  await page.getByLabel("Вакансия", { exact: true }).selectOption({ label: name });
  await page.getByRole("button", { name: "Добавить", exact: true }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.getByRole("tab", { name: /^Кандидаты/ }).click();
  await page.getByRole("button", { name, exact: true }).click();
  await page.getByRole("button", { name: "Собеседование", exact: true }).click();
  const future = new Date(Date.now() + 86400000);
  const local = new Date(future.getTime() - future.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
  await page.locator('input[type="datetime-local"]').fill(local);
  await page.getByRole("button", { name: "Назначить", exact: true }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.getByRole("button", { name, exact: true }).click();
  await page.getByLabel("Этап подбора").selectOption("offer");
  await page.getByRole("button", { name: "Сохранить", exact: true }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.getByRole("button", { name, exact: true }).click();
  await page.getByRole("button", { name: "Оформить сотрудника" }).click();
  await page.getByLabel("Дата выхода", { exact: true }).fill(local.slice(0, 10));
  await page.getByRole("button", { name: "Оформить", exact: true }).click();
  await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Назначить обучение" }).click();
  await page.getByLabel("Урок", { exact: true }).selectOption({ label: "Знакомство с компанией" });
  await page.getByLabel("Срок выполнения", { exact: true }).fill(local.slice(0, 10));
  await page.getByRole("button", { name: "Назначить", exact: true }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await expect(page.getByRole("heading", { name: "Знакомство с компанией" })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("heading", { name: "Знакомство с компанией" })).toBeVisible();
  await page.getByRole("tab", { name: "История подбора" }).click();
  await expect(page.locator(".academy-history li").filter({ hasText: "Оформлен сотрудником" })).toBeVisible();
  const employeeId = page.url().split("/").at(-1)!;
  const token = await page.evaluate(() => localStorage.getItem("access_token"));
  const headers = { Authorization: `Bearer ${token}` };
  const assignments = await page.request.get(`/api/v1/assignments/?employee_id=${employeeId}`, { headers });
  expect(assignments.ok()).toBeTruthy();
  const assignment = (await assignments.json())[0];
  const completion = await page.request.patch(`/api/v1/assignments/${assignment.id}/status`, { headers, data: { status: "completed" } });
  expect(completion.ok()).toBeTruthy();
  await page.reload();
  await expect(page.getByText("100%", { exact: true })).toBeVisible();
  await page.getByRole("tab", { name: "Профиль", exact: true }).click();
  await page.getByRole("button", { name: "Редактировать профиль", exact: true }).click();
  await page.getByLabel("ФИО *", { exact: true }).fill(`${name} обновлено`);
  await page.getByLabel("Телефон", { exact: true }).fill("123456");
  await page.getByLabel("Статус", { exact: true }).selectOption("probation");
  await page.getByLabel("Должность", { exact: true }).selectOption("");
  await page.getByLabel("Дата приёма", { exact: true }).fill("2026-10-01");
  await page.getByRole("button", { name: "Сохранить", exact: true }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.reload();
  await expect(page.getByRole("heading", { name: `${name} обновлено`, exact: true })).toBeVisible();
  await expect(page.getByText("100%", { exact: true })).toBeVisible();
  await page.getByRole("tab", { name: "Профиль", exact: true }).click();
  await page.getByRole("button", { name: "Редактировать профиль", exact: true }).click();
  await expect(page.getByLabel("Статус", { exact: true })).toHaveValue("probation");
  await expect(page.getByLabel("Должность", { exact: true })).toHaveValue("");
  await expect(page.getByLabel("Телефон", { exact: true })).toHaveValue("123456");
  await expect(page.getByLabel("Дата приёма", { exact: true })).toHaveValue("2026-10-01");
  await page.getByRole("button", { name: "Отмена", exact: true }).click();
  const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAEUlEQVR4nGP8z4AATEhsPBwAM9EBBzDn4UwAAAAASUVORK5CYII=", "base64");
  await page.getByLabel("Загрузить фото сотрудника", { exact: true }).setInputFiles({ name: "photo.png", mimeType: "image/png", buffer: png });
  const photo = page.getByRole("img", { name: `Фото ${name} обновлено`, exact: true });
  await expect(photo).toBeVisible();
  await expect.poll(() => photo.evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0);
  await page.reload();
  await page.getByRole("tab", { name: "Профиль", exact: true }).click();
  await expect(photo).toBeVisible();
  await page.getByLabel("Загрузить фото сотрудника", { exact: true }).setInputFiles({ name: "replacement.png", mimeType: "image/png", buffer: png });
  await expect(page.getByRole("button", { name: "Заменить фото", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Удалить фото", exact: true }).click();
  await expect(photo).toHaveCount(0);
  await expect(page.getByText("100%", { exact: true })).toBeVisible();
});
